### ISSUE TITLE
Const correctness in C++98 codegen

### ISSUE THREAD

**Issue by steve-o** [real-logic/simple-binary-encoding#152]
The C++98 generated code should support a const pointer on decode.  It may be limited to C++11 or 14 but I'm sure the MessageHeader could detect a const buffer and self modify to disable the setters.
```
	hdr.wrap (const_cast<char*> (buffer), 0, version, length);
	msg.wrapForDecode (const_cast<char*> (buffer), hdr.size(), hdr.blockLength(), hdr.version(), length);
```

**Comment by tmontgomery** [comment]
Unfortunately, due to the statefulness of a decoder in tracking position, it is not possible to take this approach. Using `const_cast` to update position on getters is fine, but it is undefined behavior to do this on a `const` declared codec. See the example at http://en.cppreference.com/w/cpp/language/const_cast Thus, it isn't a good idea to take this tact. Instead, #271 will eventually be the solution and generate decoder and encoder versions.

Closing this as invalid.
