### ISSUE TITLE
[C++] Generate message pretty printers

### ISSUE THREAD

**Issue by arnetheduck** [real-logic/simple-binary-encoding#178]
It would be very convenient if the generated code could also pretty print (to string, ostream or whatever) in some suitable name=value format (FIX, json, protobuf ShortDebugString to name a few candidates), for debugging / logging purposes.

**Comment by lcs777** [comment]
I dipped my toe in the water with PR #296 .  I am thinking of expanding this work by adding the ability to print to an ostream (for enums, options, decimals) as well as having a toJson() method for each message, since JSON seems the most useful human readable encoding.

If anyone has any suggestions, please let me know.

**Comment by MatthiasKauer** [comment]
Hi,
I'm interested in working on this.
Is it still relevant? Is someone else working on it?

**Comment by mjpt777** [comment]
@MatthiasKauer We would be happy accepting a PR for this.
