### ISSUE TITLE
Add String convenience methods for var data

### ISSUE THREAD

**Issue by mjpt777** [real-logic/simple-binary-encoding#221]
Add convenience methods to get and put a String for var data fields containing characters.

**Comment by David-Wales** [comment]
Am I right in my understanding of this ticket;

That char datatypes specified in the Codec's XML file should generate an equivalent overloaded put method that takes a String as an argument instead of a byte array and an equivalent get method that returns a string instead of using a for loop to return by character. 

for example 

```
<type name="VehicleCode" primitiveType="char" length="6"/>
```


Pehaps generating some method as such:-
``` 
//Maybe not need to srcOffset argument in this case
public Car putVehicleCode(final String src, final int srcOffset)
```

and some kind of method on the codec that allows the following to be circumvented
```
        for (int i = 0, size = Car.vehicleCodeLength(); i < size; i++)
        {
            sb.append((char)car.vehicleCode(i));
        }
```


Thank you

**Comment by tmontgomery** [comment]
You are correct. This is a usability enhancement to make it easier to use. It is more akin to grabbing the bytes into a temporary byte buffer, though. Then constructing the string from that.

**Comment by mjpt777** [comment]
I added the String convenience methods for var data. Maybe it should also be added for char arrays.
