### ISSUE TITLE
Does SBE support unions or tagged unions?

### ISSUE THREAD

**Issue by RajivSignal** [real-logic/simple-binary-encoding#232]
I have a union that can either be an uint64 or a double. I represent it in the following way in C:
    struct `__attribute__ ((__packed__))` Value {
        union {
        int64_t long_value;
        double double_value;
      } value;
      uint8_t long_or_double;
    };
Can I emulate this in SBE?

**Comment by DoDaLi** [comment]
Does SBE support unions now?

**Comment by DoDaLi** [comment]
> Nope

Thanks

**Comment by haydenflinner** [comment]
Are there any ways to opt-in to reduce the per message header overhead?

For example the schema id could go, since one can often assume based on context (connection data came from, or the message its nested in) the schema. And if one could opt out of the var length count and repeated field count in exchange for never using those on a particular message/template, we'd save a few more bytes. 

Chuck enough of these fields out and SBE seems to be able to describe decoding quite a few custom binary formats, which are often a type/length prefix followed by some statically arranged fields. Just trying to see how close to a Flatbuf 'struct' or raw C struct one could get or should be allowed to get.

Tbh I guess none of the message fields are strictly necessary; skipping them all would let SBE be used for tightly coupled (i.e. exact message is known) shared mem communication between two processes in different languages, with zero overhead vs a handwritten impl in each language. Then adding in a length prefix lets one copy without slicing. And template Id brings in multiple msg types.

This alone isn't a huge win compared to the complexity, it just allows use in more cache-line sensitive (and tightly controlled) places.

But if carried all the way to the ends of this issue: a basic tagged union as a new SBE primitive, like std::variant, would have clear value. And doesn't require any of the above complexity, as we're hand selecting a small subset of the common message header for this one common use case. Many languages support tagged unions like this. Just a leading type enum and a following field for whatever the value is, always big enough to fit the biggest value. A tagged union containing a template or something variably sized would not be valid, since I believe by SBE wisdom these should instead be lifted to the protocol level. But a simple scalar tagged union seems like it could work as an extension. The surefire desire for unions that include varlen strings loops back into the first paragraph on opting into length prefix while opting out of everything else for specific templates.
