### ISSUE TITLE
Must process repeating groups in order?

### ISSUE THREAD

**Issue by roji** [real-logic/simple-binary-encoding#240]
Coding in C#, it seems that repeating groups must be traversed in their order of appearance in the schema. In other words, group B was specified before group A. I tried to skip over group A and traverse group B directly and got corrupted data. Simply looping over group A before accessing group B solved the problem.

If this is the desired behavior, please make this very clear in the documentation and consider throwing an exception for incorrect traversal?

**Comment by odeheurles** [comment]
This is by design, and the same behavior applies in java and C++.

You must read fields, then groups, then variable length fields, in the order specified in the schema. We do not throw exceptions as it would require inserting additional branching in the code (I think we talked about that some time ago and decided yo not do it).

Regarding the doc this requirement appears in the design principles but I agree it should probably be highlighted in a few more places. Martin, Todd what do you think?

Olivier

**Comment by roji** [comment]
Thanks for the quick response. A much more visible mention would definitely save a lot of frustration to newcomers...

I definitely understand wanting to avoid the performance hit associated with the additional branching. May I suggest adding these checks with #IF DEBUG in C# and Java? I admit the value here is limited because people will be normally coding against the release build, but it may still help.

**Comment by roji** [comment]
One idea: when doing code-generation, you can simply place #IF DEBUG around sanity checks such as the proper order. This way if a user compiles your code-generated classes with DEBUG they get the error checking. The same can be done in C++ with NDEBUG.

This gives users the best of both worlds: checks in debug builds without compromising on performance in release. Of course, this doesn't take care of checks in the non-generated core (i.e. SBE.dll), in which case the user would have to link to a DEBUG-compiled version. But checks in the generated code should probably provide a lot of sanity?

**Comment by tmontgomery** [comment]
I think it would be useful to add some compilable checks. C# and C++ would be useful. But Java might be slightly less desirable. We can add a static to get the optimiser to avoid it, but it might balloon the methods a good bit and cause them to not be inlined. So, somewhat tricky to do. Going to make this as an enhancement.

**Comment by JerryShea** [comment]
Similarly, if you forget to call next() before you write to a group for the first time you will get a corrupt message as the offset member variable will not have been correctly set. This is another example of something that could be checked for in debug build/debug mode.

**Comment by spoerri** [comment]
The idiomatic way to do this in Java is with assertions.

It would be nice however to be able use the API properly without having to read the schema...

Would you accept a patch to decode sequence dependent fields using callbacks instead of getters? That way SBE could invoke the callback only at the right time.

(Should we move discussion of this more ambitious feature to a new issue?)

**Comment by mjpt777** [comment]
Best to move this to a separate discussion. Messages can already be decoded with callbacks using the OTF decoder. Whatever approach is taken it should honour the design principles and preserve performance.

https://github.com/real-logic/simple-binary-encoding/wiki/Design-Principles
