### ISSUE TITLE
tag decode

### ISSUE THREAD

**Issue by rollen1960** [real-logic/simple-binary-encoding#247]
How is possible to decode a sbe message if i know the tag ?

How can I write a function like this:

IrCollection::loadFromFile(...) 
Listener::resetForDecode(...)

Field f1 = decode(const ::uint16_t schemaId_1)
Field fn = decode(const ::uint16_t schemaId_n)

Thanks

**Comment by mjpt777** [comment]
The major goal for SBE is performance both in terms of throughput and predictable latency. This style of decoding is not supported due to how inefficient it forces an implementation to be.  It requires unpredictable branching and random access which is not mechanically sympathetic to modern hardware.
