### ISSUE TITLE
[C++] Provide convenience method to interact with `std::string` for `data` fields and `char` arrays

### ISSUE THREAD

**Issue by amluto** [real-logic/simple-binary-encoding#295]
For a string (using CME's "Symbol" as an example), the generated APIs are:

* ```const char *symbol(void)```: generally incorrect and unsafe -- if the encoded field contains a maximum-length string, the returned pointer will point to an unterminated string.
* ```sbe_char_t symbol(const int index) const```: this has its range checked, but it's barely useful in practice unless you really want character-by-character access.
* ```void symbol(const int index, const sbe_char_t value)```: not a getter at all.  (In general, naming getters and setters the same thing is not very friendly to users.)
* ```int getSymbol(char *dst, const int length) const````: no more useful than any of the other APIs.
* ```static const int symbolLength(void)```: returns the static length, not the actual length.

**Comment by tmontgomery** [comment]
A convenience method for return `std::string` (using move semantics) will be evaluated for data.

**Comment by tmontgomery** [comment]
Unless I am mistaken, CME  `Symbol` is an array of char. Which has a fixed length. So, most of what is mentioned is actually incorrect. For example, the `const char *` return method is quite safe when used appropriately (since what is pointed to is a fixed length).

Encoding and decoding individual elements of an array, i would hope, makes sense.

Copying the entire array to use should also make sense.

And lastly, length should make sense since by the SBE spec, it is a static length. The actual length has no meaning for an array of static length. It is how the app interprets it.

Still, as a convenience, it would be nice if arrays of `char` types generated `std::string` as well as `data` fields.

So, I am changing the title to more accurately reflect the "general" request of `std::string` interaction.
