### ISSUE TITLE
Non-Field checks for language keywords

### ISSUE THREAD

**Issue by JeffGreen** [real-logic/simple-binary-encoding#331]
Similar to #317 (Field), we're not checking for lowerCase validation on at least SetType and EnumType (maybe others too, not sure).  

Also, I think we should have some sort of override to rename rather than just throwing an exception.  Some popular "3rd-party" templates use keywords for names and without some way to automagically rename these with an underscore or something similar, we likely won't be able to generate templates for these template files unless the xml files themselves are modified which seems like the wrong solution as there's nothing really "wrong" with having a name of "final" in the template xml.

**Comment by mjpt777** [comment]
@JeffGreen Enums and Sets get capitalised for first character. I cannot see the issue. Can you provide a worked example?

**Comment by JeffGreen** [comment]
They get capitalized in the parser, but lower-cased in the generator.  See for example `JavaGenerator.generateChoiceEncoder(String, List<Token>)` and notice that `final String choiceName = formatPropertyName(token.name())`.  The formatPropertyName function just calls toLowerFirstChar.

**Comment by mjpt777** [comment]
Maybe we should allow keywords and have an character prepended, '_' can be the default and it can be changed with a system property.

**Comment by JeffGreen** [comment]
That sounds very reasonable to me and the ability to change the default should ward off those that would wage a holy war over non-private methods starting with an underscore.

**Comment by mjpt777** [comment]
@tmontgomery Are you happy with this approach from a C++ perspective?

**Comment by tmontgomery** [comment]
Having naming conflicts with language reserved words is unclean. The better behavior is to fix the schema. But realistically, in some cases, that is not possible.

So, I'm fine with the reserved words for all languages changing the names automatically. However, I think this should be an option that is opted into. By default, this should still be a fatal error, requiring the using to explicitly request the naming change via a system property (maybe by just setting the prepending string). And even then, it should generate a WARNING. This would hopefully help promote the better behavior while leaving the option when nothing else can be done.

Prepending with a '_' is used on some OSs for some C libc functions. I would find this confusing. Instead, the default might be better to be `sbe_` or something similarly ugly.

or...

If there is no default for the prepended string, because it is activated by setting the property, then problem solved. The user must specify a prepended string or it won't generate.

**Comment by mjpt777** [comment]
I like the idea of defaulting to spitting the dummy out, then provide the option of setting a property for the prepend string for those that have no choice.

**Comment by tmontgomery** [comment]
@mjpt777 so the behavior I mentioned, you mean?

**Comment by mjpt777** [comment]
Yes

**Comment by mjpt777** [comment]
@JeffGreen Can you check the latest build and see if that works for you now?

**Comment by JeffGreen** [comment]
Yes, the change works as I expect.  It spits out:
`Exception in thread "main" java.lang.IllegalStateException: Invalid property name=final consider setting sbe.keyword.append.token` for the default case and spits out correct code when the `sbe.keyword.append.token` property is set.

**Comment by mjpt777** [comment]
Great. I've also added a test to parse and generate from the CME FixBinary market data template.
