### ISSUE TITLE
Constant char are treated as String array 

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#463]
Any update on this issue 
[https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/40](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/40)

Constant char are treated as String array in the real logic generated code. Below is generated code.

public byte crossType(final int index)
    {
        return CROSSTYPE_VALUE[index];
    }

This should have been, no index as it is of length 1.

public byte crossType()
    {
        return 51;
    }
`<type description="Cross Type" primitiveType="char" name="CrossType" semanticType="char" length="1" presence="constant">3</type>`

**Comment by mjpt777** [comment]
We have not had clarification on this. Best to ask at the FIXTrandingCommunity rather than here.

**Comment by mjpt777** [comment]
I propose that we change this so that if the length is one and a constant is provided then it is a char. If the length is greater than 1 then it is treated as a fix char array with the values between constant value length and indicated length filled with NULs.

**Comment by mjpt777** [comment]
To help think about the issue. A constant is best used when the field later intends to have a variable. So it is there as a place holder so that when the variable comes along then the using code does not have to change. Single value char constants are often better served as a enum so more likely a char type that is constant would be an array.
