### ISSUE TITLE
SBE for C11/C99

### ISSUE THREAD

**Issue by krisskross** [real-logic/simple-binary-encoding#538]
Hi

I would like to know if there's an easy way to hack the code generator to generate code for C11/C99? Or maybe if its possible to use the C++ code from C?

Cheers,
-Kristoffer

**Comment by tmontgomery** [comment]
No real easy way to hack it since it generates classes with stateful methods and not simple structs. To use C++ code from C requires linking in the C++ runtime library. Also, creating a number of functions. Doable, but not entirely without a good bit of work.

A brand new C generator would be less work than a C wrapper over C++ or hacking the C++ generator.

**Comment by krisskross** [comment]
Ok, thanks!
