### ISSUE TITLE
C++: std::uint64_t vs std::size_t

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#634]
Hello Devs,

Is there a reason to use `std::uint64_t` for indexes/sizes in generated c++ code instead of `std::size_t`?

Thanks

**Comment by mjpt777** [comment]
Simplicity of having one type cover all cases. It could be simplified if someone was interested in sponsoring the work.

**Comment by ksergey** [comment]
There is mix of `std::size_t`/`std::uint64_t`

**Comment by mjpt777** [comment]
The only methods that return a `std::size_t` are the ones for the size of a type. Are there others?

**Comment by tmontgomery** [comment]
The codecs use those types so that:

- the class has a known size and consistent across platforms, and
- are large enough for every use case across those platforms, etc.

The method to the madness is that the specific sizes are there so that they are consistent across platforms, compilers, and CPU architectures instead of being varied.
