### ISSUE TITLE
Support for adding "implements Interface"/"extends Superclass" to generated code

### ISSUE THREAD

**Issue by sortakool** [real-logic/simple-binary-encoding#99]
Is there a way to have the generated Java classes implement an interface and/or extend a superclass?

**Comment by imaginarymike** [comment]
I'd also like to see this feature for three main reasons.  First, maintaining two definitions is error prone.  Second, although there are alternatives there's no workaround, it's impossible for codec classes to inherit from a class or implement an interface.  Last, and I'm hesitant to argue performance with this group, double allocation doesn't seem to align well with relevant efficiency goals.  True they're small objects, but seems like a significant amount of garbage for something like an event system processing 1m/sec.

Most importantly, thank you for the brilliant encoding software, immensely valuable and sincerely appreciated.

**Comment by tmontgomery** [comment]
Thanks! Glad you like it!

I'm not following the double allocation point. SBE usage is to reuse the codec objects. So, if you are allocating one on each event, that is a lot of unnecessary work being done.

I agree on the error prone aspect of multiple definitions.

As it has been a while since this was discussed, my memory is a bit rusty...

What would be the concrete proposal here? Is it to optionally have generated classes simply add "implements interface" and/or "extends superclass" on the line? Without adding any specific code within the class to make it correct/compilable?

**Comment by donmendelson** [comment]
It seems I have had this same discussion with folks for years regarding relationships between business classes such order or execution and the objects used to serialize or persist them. First, I would say that an execution message does not have an **IS A** relationship with an execution. So inheritance or realization of an interface is not appropriate. Furthermore, an execution can be associated to multiple objects, such a message encoder and also a persistence class for storing an execution in a database table. 

My recommendation is to use a strategy pattern for associating an event to a message when needed or associating to a database persister in another case.

**Comment by mjpt777** [comment]
@donmendelson +1

**Comment by imaginarymike** [comment]
Thanks for all the responses and suggestions.  I didn’t consider that the buffers were reused in terms of the double allocation point.  After reading the comments and rereading the FIX SBE blog entry the suggested approach makes sense, I’ll go that route.
